# Algorithms Homework 1

In [1]:
# Load required Python libraries.
import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg

## Linear Algebra Review

### Exact solution

Solve the following system of linear equations BY HAND with exact arithmetic:

$$3 x_1 + 2 x_2 + x_3 = 6$$
$$-x_1 + 4 x_2 + 5x_3 = 8$$
$$2x_1 -8 x_2 + 10 x_3 = 4$$

Turn in your work via Gradescope.

### Solve using the inverse

Solve the same linear system by first inverting the matrix A and performing matrix multiplication. You should use Python and SciPy.
* Tutorials and documentation: https://docs.scipy.org/doc/scipy-1.1.0/reference/tutorial/linalg.html

$A\mathbf{x} = \mathbf{b} \Rightarrow \mathbf{x} = A^{-1}\mathbf{b}$

In [52]:
# Add your solution here
A = np.array([[3,2,1],[-1,4,5],[2,-8,10]])
print('A = \n', A)
b = np.array([6,8,4])
print('b = \n', b)

A = 
 [[ 3  2  1]
 [-1  4  5]
 [ 2 -8 10]]
b = 
 [6 8 4]


In [53]:
# Add your solution here
x = np.linalg.inv(A) @ b
print(x)

[1. 1. 1.]


### Solve using LU decomposition

Do the following:
1. Use ``linalg.lu(A)`` to calculate $P$, $L$, and $U$.
2. Write a function to solve any linear system given the factorization and $b$. You may not use ```linalg.solve``` in your function. Instead, you should write loops to implement back substitution.
3. Use your function to solve the linear system.


In [55]:
# You need to define the matrix A1 somewhere (or change the variable name)
A1 = np.array([[3,2,1],[-1,4,5],[2,-8,10]])
P, L, U = linalg.lu(A1)

# Permutation matrix
print(P)

# Lower diagonal matrix
print(L)

# Upper diagonal matrix
print(U)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [-0.33333333 -0.5         1.        ]]
[[ 3.          2.          1.        ]
 [ 0.         -9.33333333  9.33333333]
 [ 0.          0.         10.        ]]


Tip: We discussed this algorithm in class. First write pseudocode on paper (how to translate our notes into loops, logical statements, etc.?). Once you are happy with the logic, code it up.

In [66]:
# Write function here.
def my_lu_solve(P, L, U, b, LOUD=True):
    ''' 
    Solves linear system Ax = b given PLU decomposition of A
    
    Arguments:
        P - N by N permutation matrix
        L - N by N lower triangular matrix with 1 on diagonal
        U - N by N upper triangular matrix
        b - N by 1 vector
    
    Returns:
        x - N by 1 solution to linear system
    '''
    
    # Define x so this does not give an error. You can delete the line below.
    
    # Add your solution here
    
    # forward sub for y: Ly = Pb
    Pb = P@b
    n = len(Pb)
    y = [0]*n
    
    if LOUD:
        print('Forward solve...')
    
    for i in range(n):
        y[i] = Pb[i]
        
        for j in range(i):
            y[i] -= L[i,j]*y[j]
        
        y[i] /= L[i,i]
        
        if LOUD:
            print('y [',i,'] = ', y[i])
    
    # backward sub for x: Ux = y
    x = [0]*n
    
    if LOUD:
        print('Backward solve...')
    
    for i in range(n-1,-1,-1):
        x[i] = y[i]
        
        for j in range(i+1,n):
            x[i] -= U[i,j]*x[j]
       
        x[i] /= U[i,i]
        
        if LOUD:
            print('x [',i,'] = ', x[i])
        
    return x

In [68]:
x = my_lu_solve(P, L, U, b, LOUD=True)

Forward solve...
y [ 0 ] =  6.0
y [ 1 ] =  0.0
y [ 2 ] =  10.0
Backward solve...
x [ 2 ] =  1.0
x [ 1 ] =  1.0
x [ 0 ] =  1.0


### Solve using `linalg.solve`


In [7]:
# Add your solution here
x = np.linalg.solve(A,b)
print(x)

[1. 1. 1.]


## Eigenvalues

### Calculate eigenvalues by hand (on paper)

Calculate the eigenvalues for the following matrix:

$$
A = \begin{bmatrix} 0 & -4 & -6 \\ -1 & 0 & -3 \\ 1 & 2 & 5 \end{bmatrix}
$$

You may need to do this for a small system on an exam to characterize stationary points of an optimization problem. Hence I would like you to practice at least once on the homework.

### Calculate eigenvalues using `linalg.eig`

Calculate the eigenvalues and corresponding (right) eigenvectors.

In [8]:
# Add your solution here
A2 = np.array([[0, -4, -6],[-1,0,-3],[1,2,5]])
print('A2 = \n', A2)

A2 = 
 [[ 0 -4 -6]
 [-1  0 -3]
 [ 1  2  5]]


In [9]:
# Add your solution here
λ = linalg.eig(A2)
print('eigenvalues: \n', λ[0], '\n eigenvectors: \n', λ[1])

eigenvalues: 
 [1.+0.00000000e+00j 2.+5.64696828e-16j 2.-5.64696828e-16j] 
 eigenvectors: 
 [[-0.81649658+0.j         -0.89295527+0.j         -0.89295527-0.j        ]
 [-0.40824829+0.j          0.01831462-0.28921177j  0.01831462+0.28921177j]
 [ 0.40824829+0.j          0.28544201+0.19280785j  0.28544201-0.19280785j]]


### Definiteness

Based on your calculations above, is this matrix
1. positive definite
2. positive semi definite
3. negative definite
4. negative semi definite
5. indefinite or
6. cannot say without additional calculations?

Briefly comment to justify your answer.

*Note*: In this class, "briefly comment" means write a few sentences, sketch a picture, write an equation or some combination... whichever you feel is necessary to succinctly provide justification.

### Singular Value Decomposition

**TODO:** Make this a separate problem (after the assignment is turned in this year).

### SVD calculation using `linalg.svd`

Calculate the singular value decomposition of the following matrix using `linalg.svd`:

$$
A_3 = \begin{bmatrix} 1 & 2 & 0 & -1 \\ 2 & 4 & 10^{-6} & -2 \\ 0 & 2 & -1 & 10^{-3} \end{bmatrix}
$$

In [73]:
# Add your solution here
A3 = np.array([[1,2,0,-1],[2,4,10**(-6),-2],[0,2,-1,10**(-3)]])
print('A = \n', A3)

A = 
 [[ 1.e+00  2.e+00  0.e+00 -1.e+00]
 [ 2.e+00  4.e+00  1.e-06 -2.e+00]
 [ 0.e+00  2.e+00 -1.e+00  1.e-03]]


In [11]:
# Add your solution here


### Condition number
What is the condition number of the matrix? Calculate it two ways:
1. Using SVD results
2. Using ``np.linalg.cond()``

In [12]:
# Add your solution here

In [13]:
# Add your solution here

### Linear system

Consider the linear system $A_4 \cdot x = b$ with $b = [1, 0, 3]^T$ and

$$
A_4 = \begin{bmatrix} 1 & 2 & 0 \\ 2 & 4 & 10^{-1} \\ 0 & 2 & -1 \end{bmatrix} ~.
$$

Approximately how much uncertainty $||\Delta b||_2$ can you tolerate if you want the uncertainty $||\Delta x||_2$ to be less than $10^{-2}$?


In [14]:
# Add your solution here

**Answer**:

### Make it singular


Do/answer the following:
1. Propose a change to a single entry in $A_4$ to make it singular.
2. What are the singular values and condition number after this change?
3. What can you say about the solution to $A_4 \cdot x=b$ after the change?

**Answer:**

## Convexity

Please turn in via Gradescope.

### Determine if the following functions are convex

1. $x^2 + ax + b, ~x \in \mathbb{R}$
2. $x^3, ~x \in \mathbb{R}$
3. $| x |, ~ x \in [ -5, 5]$
4. $x + y, ~ x \in \mathbb{R}, ~ y \in \mathbb{R}$
5. $x \cdot y, ~ x \in \mathbb{R}, ~ y \in \mathbb{R}$
6. $\log(x), ~ x \in (0,1]$

### Prove the following properties

Consider twice differentiable function $f(x): \mathbb{R}^n \rightarrow \mathbb{R}$.

Recall that $f(x)$ is convex on $x \in \mathbb{R}^n$ if and only if

$f(x+p) \geq f(x) + \nabla f(x)^T p$ for all $x, p \in \mathbb{R}^n$


#### PSD implies Convexity

Prove that if $\nabla^2 f(x)$ is positive semidefinite for all $x \in \mathbb{R}^n$, then $f(x)$ must be convex.


#### Convexity implies PSD

Prove that if $f(x)$ is convex then $\nabla^2 f(x)$ must be positive semidefinite.

#### PD implies Strictly Convex

Prove that if $\nabla^2 f(x)$ is positive definite for all $x \in \mathbb{R}^n$, then $f(x)$ must be strictly convex.